apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: helloworld
build:
  local:
    push: true
  artifacts:
    - image: shkrishnamoorthy/helloworld-spring
      jib:
        args:
          - -Pjib
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - knative-service.yaml
