apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: helloworld
build:
  local:
    push: true
  artifacts:
    - image: shkrishnamoorthy/helloworld-spring
      # buildpacks:
      #   builder: "gcr.io/buildpacks/builder:v1"
      jib:
        args:
          - -Pjib
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - ./kustomize/knative-service.yaml
